steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=$_VITE_GOOGLE_CLIENT_ID'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/alfred-frontend'
      - '.'
images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/alfred-frontend'
