steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=$_VITE_GOOGLE_CLIENT_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/alfred-frontend'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/alfred-frontend'
